### ISSUE TITLE
Invalid value for 'page_action.default_icon'

### ISSUE THREAD

**Issue by greghesp** [atosorigin/crx-bluekiwi-notifications#16]
Error message when loading extension into Chrome

Invalid value for 'page_action.default_icon'

**Comment by anthonylau** [comment]
where is the 'page_action.default_icon' ? 
I can't see the error

**Comment by greghesp** [comment]
In chrome.

Load extension -> point to development folder and click load.   It should just load the extension without issue

**Comment by chiefumpire** [comment]
Cannot replicate the error. You can try the reload link.

**Comment by greghesp** [comment]
Closing.  Issue was due to running Chromium Channel Browser, not Chrome!
