### ISSUE TITLE
Inputting bK URL when not signed in causes validation issue

### ISSUE THREAD

**Issue by greghesp** [atosorigin/crx-bluekiwi-notifications#17]
If user is not signed into bK, options page gives URL validation issue.  This makes it look like there is an issue with the URL.

Add additional notification to state that user is not logged into URL.  
Make URL validation check that URL is in URL format and to strip trailing slash

**Comment by anthonylau** [comment]
single trailing slash is already stripped

**Comment by greghesp** [comment]
Add timeout to validation.  Otherwise it gets stuck in a loop with no way to cancel when URL in invalid
![screen shot 2013-05-22 at 18 26 39](https://f.cloud.github.com/assets/768908/549967/d7a1e05e-c304-11e2-92bc-5fba2716d2c7.png)

**Comment by anthonylau** [comment]
> Add additional notification to state that user is not logged into URL.

I think use a gray icon maybe better?
