### ISSUE TITLE
add option for home button URL

### ISSUE THREAD

**Issue by anthonylau** [atosorigin/crx-bluekiwi-notifications#18]

**Comment by greghesp** [comment]
The home button URL should link to the Zen install which it does, unless it is hardcoded in.  Will have to look.

**Comment by chiefumpire** [comment]
Maybe we would add customizable  menu buttons or load the tab list if possible.

**Comment by greghesp** [comment]
What would be the reason for adding menu buttons?  At the moment there is only a notifications feed so there is no where else to go.  The options page is now a separate page

**Comment by chiefumpire** [comment]
I just see people keep asking how to change the default landing page.
