### ISSUE TITLE
2 tabs needed : Spaces list (sorted) and Notifications

### ISSUE THREAD

**Issue by pdecrocq** [atosorigin/crx-bluekiwi-notifications#22]
Hi,
First of all thanks for this great add-in !
I would need two automatically refreshed tabs in Chrome :
1. (sorted) List of BK spaces
2. list notifications
Is this possible ?
Thanks
-Pierre

**Comment by anthonylau** [comment]
2 browser tabs?

**Comment by pdecrocq** [comment]
Well, actually, by "tabs" I mean either bookmarks bar pulldown, or extension icons. Clearer ?

**Comment by anthonylau** [comment]
We have notification list and sorted space list and they will be updated everytime when you click the extension icon.

**Comment by pdecrocq** [comment]
Agreed, but that's two clicks ;-) ! can we have 2 icons or be able to choose the default one displayed ?

**Comment by anthonylau** [comment]
We can't have 2 icons but we can provide an option to choose the default one.

**Comment by pdecrocq** [comment]
Would be great ! Looking forward to it ! Thanks

**Comment by anthonylau** [comment]
available in v2.3.1.0

**Comment by pdecrocq** [comment]
Thanks a lot !

**Comment by anthonylau** [comment]
You are welcome :)
