### ISSUE TITLE
Review License

### ISSUE THREAD

**Issue by anthonylau** [atosorigin/crx-bluekiwi-notifications#8]

**Comment by anthonylau** [comment]
JQuery
https://jquery.org/license/
Boostrap
https://github.com/twitter/bootstrap#copyright-and-license

**Comment by greghesp** [comment]
Not sure what is needed here?

**Comment by anthonylau** [comment]
Need review the license terms. What should we do if use these 3rd party libraries.(publish with what license, need indicate the name/author/license of 3rd party library or not)

**Comment by greghesp** [comment]
Just had a quick look and it would appear that as long as you leave the copyright headers in the relevant files intact, you are fine.  Let me know your thoughts

**Comment by anthonylau** [comment]
That's great. Should we make our code under a license?
